name: Deployment Pipeline

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npx playwright test
      - name: Deploy
        run: |
          echo "Deploying to production..."
          echo "Deployed!"
